// Generated by generate_glibc_abi.py — do not edit.
// Regenerate with: python3 generate_glibc_abi.py | zig fmt --stdin > glibc_abi.zig
//
// Each function returns the minimum glibc version that introduced the symbol
// for a given (arch, abi) target, or null if not available in glibc.

const std = @import("std");

pub fn accept4(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    return switch (arch) {
        .aarch64 => .{ .major = 2, .minor = 17, .patch = 0 },
        .aarch64_be => .{ .major = 2, .minor = 17, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .arm => .{ .major = 2, .minor = 10, .patch = 0 },
        .armeb => .{ .major = 2, .minor = 10, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        .m68k => .{ .major = 2, .minor = 10, .patch = 0 },
        .mips => .{ .major = 2, .minor = 10, .patch = 0 },
        .mips64 => .{ .major = 2, .minor = 10, .patch = 0 },
        .mips64el => .{ .major = 2, .minor = 10, .patch = 0 },
        .mipsel => .{ .major = 2, .minor = 10, .patch = 0 },
        .powerpc => .{ .major = 2, .minor = 10, .patch = 0 },
        .powerpc64 => .{ .major = 2, .minor = 10, .patch = 0 },
        .powerpc64le => .{ .major = 2, .minor = 17, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .riscv64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .s390x => .{ .major = 2, .minor = 10, .patch = 0 },
        .sparc => .{ .major = 2, .minor = 10, .patch = 0 },
        .sparc64 => .{ .major = 2, .minor = 10, .patch = 0 },
        .x86 => .{ .major = 2, .minor = 10, .patch = 0 },
        .x86_64 => switch (abi) {
            .gnu => .{ .major = 2, .minor = 10, .patch = 0 },
            .gnux32 => .{ .major = 2, .minor = 16, .patch = 0 },
            else => null,
        },
        else => null,
    };
}

pub fn arc4random(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    _ = arch;
    _ = abi;
    return .{ .major = 2, .minor = 36, .patch = 0 };
}

pub fn arc4random_buf(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    _ = arch;
    _ = abi;
    return .{ .major = 2, .minor = 36, .patch = 0 };
}

pub fn arc4random_uniform(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    _ = arch;
    _ = abi;
    return .{ .major = 2, .minor = 36, .patch = 0 };
}

pub fn backtrace_symbols(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    return switch (arch) {
        .aarch64 => .{ .major = 2, .minor = 17, .patch = 0 },
        .aarch64_be => .{ .major = 2, .minor = 17, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .arm => .{ .major = 2, .minor = 4, .patch = 0 },
        .armeb => .{ .major = 2, .minor = 4, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        .m68k => .{ .major = 2, .minor = 1, .patch = 0 },
        .mips => .{ .major = 2, .minor = 2, .patch = 0 },
        .mips64 => .{ .major = 2, .minor = 2, .patch = 0 },
        .mips64el => .{ .major = 2, .minor = 2, .patch = 0 },
        .mipsel => .{ .major = 2, .minor = 2, .patch = 0 },
        .powerpc => .{ .major = 2, .minor = 1, .patch = 0 },
        .powerpc64 => .{ .major = 2, .minor = 3, .patch = 0 },
        .powerpc64le => .{ .major = 2, .minor = 17, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .riscv64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .s390x => .{ .major = 2, .minor = 2, .patch = 0 },
        .sparc => .{ .major = 2, .minor = 1, .patch = 0 },
        .sparc64 => .{ .major = 2, .minor = 2, .patch = 0 },
        .x86 => .{ .major = 2, .minor = 1, .patch = 0 },
        .x86_64 => switch (abi) {
            .gnu => .{ .major = 2, .minor = 2, .patch = 5 },
            .gnux32 => .{ .major = 2, .minor = 16, .patch = 0 },
            else => null,
        },
        else => null,
    };
}

pub fn copy_file_range(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    _ = abi;
    return switch (arch) {
        .aarch64, .aarch64_be, .arm, .armeb, .m68k, .mips, .mips64, .mips64el, .mipsel, .powerpc, .powerpc64, .powerpc64le, .riscv64, .s390x, .sparc, .sparc64, .x86, .x86_64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        else => null,
    };
}

pub fn explicit_bzero(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    _ = abi;
    return switch (arch) {
        .aarch64, .aarch64_be, .arm, .armeb, .m68k, .mips, .mips64, .mips64el, .mipsel, .powerpc, .powerpc64, .powerpc64le, .s390x, .sparc, .sparc64, .x86, .x86_64 => .{ .major = 2, .minor = 25, .patch = 0 },
        .riscv64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        else => null,
    };
}

pub fn getauxval(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    _ = abi;
    return switch (arch) {
        .arm, .armeb, .m68k, .mips, .mips64, .mips64el, .mipsel, .powerpc, .powerpc64, .s390x, .sparc, .sparc64, .x86, .x86_64 => .{ .major = 2, .minor = 16, .patch = 0 },
        .aarch64, .aarch64_be, .powerpc64le => .{ .major = 2, .minor = 17, .patch = 0 },
        .riscv64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        else => null,
    };
}

pub fn getentropy(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    _ = abi;
    return switch (arch) {
        .aarch64, .aarch64_be, .arm, .armeb, .m68k, .mips, .mips64, .mips64el, .mipsel, .powerpc, .powerpc64, .powerpc64le, .s390x, .sparc, .sparc64, .x86, .x86_64 => .{ .major = 2, .minor = 25, .patch = 0 },
        .riscv64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        else => null,
    };
}

pub fn getifaddrs(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    return switch (arch) {
        .aarch64 => .{ .major = 2, .minor = 17, .patch = 0 },
        .aarch64_be => .{ .major = 2, .minor = 17, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .arm => .{ .major = 2, .minor = 4, .patch = 0 },
        .armeb => .{ .major = 2, .minor = 4, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        .m68k => .{ .major = 2, .minor = 3, .patch = 0 },
        .mips => .{ .major = 2, .minor = 3, .patch = 0 },
        .mips64 => .{ .major = 2, .minor = 3, .patch = 0 },
        .mips64el => .{ .major = 2, .minor = 3, .patch = 0 },
        .mipsel => .{ .major = 2, .minor = 3, .patch = 0 },
        .powerpc => .{ .major = 2, .minor = 3, .patch = 0 },
        .powerpc64 => .{ .major = 2, .minor = 3, .patch = 0 },
        .powerpc64le => .{ .major = 2, .minor = 17, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .riscv64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .s390x => .{ .major = 2, .minor = 3, .patch = 0 },
        .sparc => .{ .major = 2, .minor = 3, .patch = 0 },
        .sparc64 => .{ .major = 2, .minor = 3, .patch = 0 },
        .x86 => .{ .major = 2, .minor = 3, .patch = 0 },
        .x86_64 => switch (abi) {
            .gnu => .{ .major = 2, .minor = 3, .patch = 0 },
            .gnux32 => .{ .major = 2, .minor = 16, .patch = 0 },
            else => null,
        },
        else => null,
    };
}

pub fn getrandom(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    _ = abi;
    return switch (arch) {
        .aarch64, .aarch64_be, .arm, .armeb, .m68k, .mips, .mips64, .mips64el, .mipsel, .powerpc, .powerpc64, .powerpc64le, .s390x, .sparc, .sparc64, .x86, .x86_64 => .{ .major = 2, .minor = 25, .patch = 0 },
        .riscv64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        else => null,
    };
}

pub fn memmem(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    return switch (arch) {
        .aarch64 => .{ .major = 2, .minor = 17, .patch = 0 },
        .aarch64_be => .{ .major = 2, .minor = 17, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .arm => .{ .major = 2, .minor = 4, .patch = 0 },
        .armeb => .{ .major = 2, .minor = 4, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        .m68k => .{ .major = 2, .minor = 0, .patch = 0 },
        .mips => .{ .major = 2, .minor = 0, .patch = 0 },
        .mips64 => .{ .major = 2, .minor = 0, .patch = 0 },
        .mips64el => .{ .major = 2, .minor = 0, .patch = 0 },
        .mipsel => .{ .major = 2, .minor = 0, .patch = 0 },
        .powerpc => .{ .major = 2, .minor = 0, .patch = 0 },
        .powerpc64 => .{ .major = 2, .minor = 3, .patch = 0 },
        .powerpc64le => .{ .major = 2, .minor = 17, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .riscv64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .s390x => .{ .major = 2, .minor = 2, .patch = 0 },
        .sparc => .{ .major = 2, .minor = 0, .patch = 0 },
        .sparc64 => .{ .major = 2, .minor = 2, .patch = 0 },
        .x86 => .{ .major = 2, .minor = 0, .patch = 0 },
        .x86_64 => switch (abi) {
            .gnu => .{ .major = 2, .minor = 2, .patch = 5 },
            .gnux32 => .{ .major = 2, .minor = 16, .patch = 0 },
            else => null,
        },
        else => null,
    };
}

pub fn mkdtemp(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    return switch (arch) {
        .aarch64 => .{ .major = 2, .minor = 17, .patch = 0 },
        .aarch64_be => .{ .major = 2, .minor = 17, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .arm => .{ .major = 2, .minor = 4, .patch = 0 },
        .armeb => .{ .major = 2, .minor = 4, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        .m68k => .{ .major = 2, .minor = 2, .patch = 0 },
        .mips => .{ .major = 2, .minor = 2, .patch = 0 },
        .mips64 => .{ .major = 2, .minor = 2, .patch = 0 },
        .mips64el => .{ .major = 2, .minor = 2, .patch = 0 },
        .mipsel => .{ .major = 2, .minor = 2, .patch = 0 },
        .powerpc => .{ .major = 2, .minor = 2, .patch = 0 },
        .powerpc64 => .{ .major = 2, .minor = 3, .patch = 0 },
        .powerpc64le => .{ .major = 2, .minor = 17, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .riscv64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .s390x => .{ .major = 2, .minor = 2, .patch = 0 },
        .sparc => .{ .major = 2, .minor = 2, .patch = 0 },
        .sparc64 => .{ .major = 2, .minor = 2, .patch = 0 },
        .x86 => .{ .major = 2, .minor = 2, .patch = 0 },
        .x86_64 => switch (abi) {
            .gnu => .{ .major = 2, .minor = 2, .patch = 5 },
            .gnux32 => .{ .major = 2, .minor = 16, .patch = 0 },
            else => null,
        },
        else => null,
    };
}

pub fn posix_fadvise(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    return switch (arch) {
        .aarch64 => .{ .major = 2, .minor = 17, .patch = 0 },
        .aarch64_be => .{ .major = 2, .minor = 17, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .arm => .{ .major = 2, .minor = 4, .patch = 0 },
        .armeb => .{ .major = 2, .minor = 4, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        .m68k => .{ .major = 2, .minor = 2, .patch = 0 },
        .mips => .{ .major = 2, .minor = 2, .patch = 0 },
        .mips64 => .{ .major = 2, .minor = 2, .patch = 0 },
        .mips64el => .{ .major = 2, .minor = 2, .patch = 0 },
        .mipsel => .{ .major = 2, .minor = 2, .patch = 0 },
        .powerpc => .{ .major = 2, .minor = 2, .patch = 0 },
        .powerpc64 => .{ .major = 2, .minor = 3, .patch = 0 },
        .powerpc64le => .{ .major = 2, .minor = 17, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .riscv64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .s390x => .{ .major = 2, .minor = 2, .patch = 0 },
        .sparc => .{ .major = 2, .minor = 2, .patch = 0 },
        .sparc64 => .{ .major = 2, .minor = 2, .patch = 0 },
        .x86 => .{ .major = 2, .minor = 2, .patch = 0 },
        .x86_64 => switch (abi) {
            .gnu => .{ .major = 2, .minor = 2, .patch = 5 },
            .gnux32 => .{ .major = 2, .minor = 16, .patch = 0 },
            else => null,
        },
        else => null,
    };
}

pub fn posix_fallocate(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    return switch (arch) {
        .aarch64 => .{ .major = 2, .minor = 17, .patch = 0 },
        .aarch64_be => .{ .major = 2, .minor = 17, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .arm => .{ .major = 2, .minor = 4, .patch = 0 },
        .armeb => .{ .major = 2, .minor = 4, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        .m68k => .{ .major = 2, .minor = 2, .patch = 0 },
        .mips => .{ .major = 2, .minor = 2, .patch = 0 },
        .mips64 => .{ .major = 2, .minor = 2, .patch = 0 },
        .mips64el => .{ .major = 2, .minor = 2, .patch = 0 },
        .mipsel => .{ .major = 2, .minor = 2, .patch = 0 },
        .powerpc => .{ .major = 2, .minor = 2, .patch = 0 },
        .powerpc64 => .{ .major = 2, .minor = 3, .patch = 0 },
        .powerpc64le => .{ .major = 2, .minor = 17, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .riscv64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .s390x => .{ .major = 2, .minor = 2, .patch = 0 },
        .sparc => .{ .major = 2, .minor = 2, .patch = 0 },
        .sparc64 => .{ .major = 2, .minor = 2, .patch = 0 },
        .x86 => .{ .major = 2, .minor = 2, .patch = 0 },
        .x86_64 => switch (abi) {
            .gnu => .{ .major = 2, .minor = 2, .patch = 5 },
            .gnux32 => .{ .major = 2, .minor = 16, .patch = 0 },
            else => null,
        },
        else => null,
    };
}

pub fn ppoll(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    return switch (arch) {
        .aarch64 => .{ .major = 2, .minor = 17, .patch = 0 },
        .aarch64_be => .{ .major = 2, .minor = 17, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .arm => .{ .major = 2, .minor = 4, .patch = 0 },
        .armeb => .{ .major = 2, .minor = 4, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        .m68k => .{ .major = 2, .minor = 4, .patch = 0 },
        .mips => .{ .major = 2, .minor = 4, .patch = 0 },
        .mips64 => .{ .major = 2, .minor = 4, .patch = 0 },
        .mips64el => .{ .major = 2, .minor = 4, .patch = 0 },
        .mipsel => .{ .major = 2, .minor = 4, .patch = 0 },
        .powerpc => .{ .major = 2, .minor = 4, .patch = 0 },
        .powerpc64 => .{ .major = 2, .minor = 4, .patch = 0 },
        .powerpc64le => .{ .major = 2, .minor = 17, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .riscv64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .s390x => .{ .major = 2, .minor = 4, .patch = 0 },
        .sparc => .{ .major = 2, .minor = 4, .patch = 0 },
        .sparc64 => .{ .major = 2, .minor = 4, .patch = 0 },
        .x86 => .{ .major = 2, .minor = 4, .patch = 0 },
        .x86_64 => switch (abi) {
            .gnu => .{ .major = 2, .minor = 4, .patch = 0 },
            .gnux32 => .{ .major = 2, .minor = 16, .patch = 0 },
            else => null,
        },
        else => null,
    };
}

pub fn reallocarray(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    _ = abi;
    return switch (arch) {
        .aarch64, .aarch64_be, .arm, .armeb, .m68k, .mips, .mips64, .mips64el, .mipsel, .powerpc, .powerpc64, .powerpc64le, .s390x, .sparc, .sparc64, .x86, .x86_64 => .{ .major = 2, .minor = 26, .patch = 0 },
        .riscv64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        else => null,
    };
}

pub fn strchrnul(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    return switch (arch) {
        .aarch64 => .{ .major = 2, .minor = 17, .patch = 0 },
        .aarch64_be => .{ .major = 2, .minor = 17, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .arm => .{ .major = 2, .minor = 4, .patch = 0 },
        .armeb => .{ .major = 2, .minor = 4, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        .m68k => .{ .major = 2, .minor = 1, .patch = 1 },
        .mips => .{ .major = 2, .minor = 2, .patch = 0 },
        .mips64 => .{ .major = 2, .minor = 2, .patch = 0 },
        .mips64el => .{ .major = 2, .minor = 2, .patch = 0 },
        .mipsel => .{ .major = 2, .minor = 2, .patch = 0 },
        .powerpc => .{ .major = 2, .minor = 1, .patch = 1 },
        .powerpc64 => .{ .major = 2, .minor = 3, .patch = 0 },
        .powerpc64le => .{ .major = 2, .minor = 17, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .riscv64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .s390x => .{ .major = 2, .minor = 2, .patch = 0 },
        .sparc => .{ .major = 2, .minor = 1, .patch = 1 },
        .sparc64 => .{ .major = 2, .minor = 2, .patch = 0 },
        .x86 => .{ .major = 2, .minor = 1, .patch = 1 },
        .x86_64 => switch (abi) {
            .gnu => .{ .major = 2, .minor = 2, .patch = 5 },
            .gnux32 => .{ .major = 2, .minor = 16, .patch = 0 },
            else => null,
        },
        else => null,
    };
}

pub fn strlcat(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    _ = arch;
    _ = abi;
    return .{ .major = 2, .minor = 38, .patch = 0 };
}

pub fn strlcpy(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    _ = arch;
    _ = abi;
    return .{ .major = 2, .minor = 38, .patch = 0 };
}

pub fn strndup(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    return switch (arch) {
        .aarch64 => .{ .major = 2, .minor = 17, .patch = 0 },
        .aarch64_be => .{ .major = 2, .minor = 17, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .arm => .{ .major = 2, .minor = 4, .patch = 0 },
        .armeb => .{ .major = 2, .minor = 4, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        .m68k => .{ .major = 2, .minor = 0, .patch = 0 },
        .mips => .{ .major = 2, .minor = 0, .patch = 0 },
        .mips64 => .{ .major = 2, .minor = 0, .patch = 0 },
        .mips64el => .{ .major = 2, .minor = 0, .patch = 0 },
        .mipsel => .{ .major = 2, .minor = 0, .patch = 0 },
        .powerpc => .{ .major = 2, .minor = 0, .patch = 0 },
        .powerpc64 => .{ .major = 2, .minor = 3, .patch = 0 },
        .powerpc64le => .{ .major = 2, .minor = 17, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .riscv64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .s390x => .{ .major = 2, .minor = 2, .patch = 0 },
        .sparc => .{ .major = 2, .minor = 0, .patch = 0 },
        .sparc64 => .{ .major = 2, .minor = 2, .patch = 0 },
        .x86 => .{ .major = 2, .minor = 0, .patch = 0 },
        .x86_64 => switch (abi) {
            .gnu => .{ .major = 2, .minor = 2, .patch = 5 },
            .gnux32 => .{ .major = 2, .minor = 16, .patch = 0 },
            else => null,
        },
        else => null,
    };
}

pub fn sync_file_range(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    return switch (arch) {
        .aarch64 => .{ .major = 2, .minor = 17, .patch = 0 },
        .aarch64_be => .{ .major = 2, .minor = 17, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .arm => .{ .major = 2, .minor = 6, .patch = 0 },
        .armeb => .{ .major = 2, .minor = 6, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        .m68k => .{ .major = 2, .minor = 6, .patch = 0 },
        .mips => .{ .major = 2, .minor = 6, .patch = 0 },
        .mips64 => .{ .major = 2, .minor = 6, .patch = 0 },
        .mips64el => .{ .major = 2, .minor = 6, .patch = 0 },
        .mipsel => .{ .major = 2, .minor = 6, .patch = 0 },
        .powerpc => .{ .major = 2, .minor = 6, .patch = 0 },
        .powerpc64 => .{ .major = 2, .minor = 6, .patch = 0 },
        .powerpc64le => .{ .major = 2, .minor = 17, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .riscv64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .s390x => .{ .major = 2, .minor = 6, .patch = 0 },
        .sparc => .{ .major = 2, .minor = 6, .patch = 0 },
        .sparc64 => .{ .major = 2, .minor = 6, .patch = 0 },
        .x86 => .{ .major = 2, .minor = 6, .patch = 0 },
        .x86_64 => switch (abi) {
            .gnu => .{ .major = 2, .minor = 6, .patch = 0 },
            .gnux32 => .{ .major = 2, .minor = 16, .patch = 0 },
            else => null,
        },
        else => null,
    };
}

pub fn syncfs(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    return switch (arch) {
        .aarch64 => .{ .major = 2, .minor = 17, .patch = 0 },
        .aarch64_be => .{ .major = 2, .minor = 17, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .arm => .{ .major = 2, .minor = 14, .patch = 0 },
        .armeb => .{ .major = 2, .minor = 14, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        .m68k => .{ .major = 2, .minor = 14, .patch = 0 },
        .mips => .{ .major = 2, .minor = 14, .patch = 0 },
        .mips64 => .{ .major = 2, .minor = 14, .patch = 0 },
        .mips64el => .{ .major = 2, .minor = 14, .patch = 0 },
        .mipsel => .{ .major = 2, .minor = 14, .patch = 0 },
        .powerpc => .{ .major = 2, .minor = 14, .patch = 0 },
        .powerpc64 => .{ .major = 2, .minor = 14, .patch = 0 },
        .powerpc64le => .{ .major = 2, .minor = 17, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .riscv64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .s390x => .{ .major = 2, .minor = 14, .patch = 0 },
        .sparc => .{ .major = 2, .minor = 14, .patch = 0 },
        .sparc64 => .{ .major = 2, .minor = 14, .patch = 0 },
        .x86 => .{ .major = 2, .minor = 14, .patch = 0 },
        .x86_64 => switch (abi) {
            .gnu => .{ .major = 2, .minor = 14, .patch = 0 },
            .gnux32 => .{ .major = 2, .minor = 16, .patch = 0 },
            else => null,
        },
        else => null,
    };
}

pub fn vasprintf(arch: std.Target.Cpu.Arch, abi: std.Target.Abi) ?std.SemanticVersion {
    return switch (arch) {
        .aarch64 => .{ .major = 2, .minor = 17, .patch = 0 },
        .aarch64_be => .{ .major = 2, .minor = 17, .patch = 0 },
        .arc => .{ .major = 2, .minor = 32, .patch = 0 },
        .arm => .{ .major = 2, .minor = 4, .patch = 0 },
        .armeb => .{ .major = 2, .minor = 4, .patch = 0 },
        .csky => .{ .major = 2, .minor = 29, .patch = 0 },
        .loongarch64 => .{ .major = 2, .minor = 36, .patch = 0 },
        .m68k => .{ .major = 2, .minor = 0, .patch = 0 },
        .mips => .{ .major = 2, .minor = 0, .patch = 0 },
        .mips64 => .{ .major = 2, .minor = 0, .patch = 0 },
        .mips64el => .{ .major = 2, .minor = 0, .patch = 0 },
        .mipsel => .{ .major = 2, .minor = 0, .patch = 0 },
        .powerpc => .{ .major = 2, .minor = 0, .patch = 0 },
        .powerpc64 => .{ .major = 2, .minor = 3, .patch = 0 },
        .powerpc64le => .{ .major = 2, .minor = 17, .patch = 0 },
        .riscv32 => .{ .major = 2, .minor = 33, .patch = 0 },
        .riscv64 => .{ .major = 2, .minor = 27, .patch = 0 },
        .s390x => .{ .major = 2, .minor = 2, .patch = 0 },
        .sparc => .{ .major = 2, .minor = 0, .patch = 0 },
        .sparc64 => .{ .major = 2, .minor = 2, .patch = 0 },
        .x86 => .{ .major = 2, .minor = 0, .patch = 0 },
        .x86_64 => switch (abi) {
            .gnu => .{ .major = 2, .minor = 2, .patch = 5 },
            .gnux32 => .{ .major = 2, .minor = 16, .patch = 0 },
            else => null,
        },
        else => null,
    };
}
