// Generated by generate_libc_headers.py — do not edit.
// Regenerate with: python3 generate_libc_headers.py | zig fmt --stdin > libc_headers.zig
//
// Headers that are universally available on all supported POSIX targets default
// to true and are listed once. Headers whose presence varies by OS default to
// false and are set explicitly in each per-OS detection function.

const std = @import("std");

pub const LibcHeaders = struct {
    // Availability reference:
    //
    // atomic.h:              NetBSD
    // copyfile.h:            macOS
    // crtdefs.h:             Windows (not a tracked target)
    // execinfo.h:            glibc, FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // getopt.h:              all supported targets
    // inttypes.h:            all supported targets
    // memory.h:              all supported targets
    // stdint.h:              all supported targets
    // stdlib.h:              all supported targets
    // string.h:              all supported targets
    // strings.h:             all supported targets
    // sys/epoll.h:           glibc, musl
    // sys/event.h:           FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // sys/personality.h:     glibc, musl
    // sys/prctl.h:           glibc, musl
    // sys/procctl.h:         FreeBSD 10.1+
    // sys/signalfd.h:        glibc, musl
    // sys/stat.h:            all supported targets
    // sys/types.h:           all supported targets
    // sys/ucred.h:           FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // termios.h:             all supported targets
    // unistd.h:              all supported targets
    // xlocale.h:             FreeBSD, macOS

    // Always present
    getopt_h: bool = true,
    inttypes_h: bool = true,
    memory_h: bool = true,
    stdint_h: bool = true,
    stdlib_h: bool = true,
    string_h: bool = true,
    strings_h: bool = true,
    sys_stat_h: bool = true,
    sys_types_h: bool = true,
    termios_h: bool = true,
    unistd_h: bool = true,

    // OS-specific
    atomic_h: bool = false,
    copyfile_h: bool = false,
    crtdefs_h: bool = false,
    execinfo_h: bool = false,
    sys_epoll_h: bool = false,
    sys_event_h: bool = false,
    sys_personality_h: bool = false,
    sys_prctl_h: bool = false,
    sys_procctl_h: bool = false,
    sys_signalfd_h: bool = false,
    sys_ucred_h: bool = false,
    xlocale_h: bool = false,
};

pub fn detect(target: std.Target) LibcHeaders {
    return switch (target.os.tag) {
        .linux => detectLinux(target),
        .macos, .ios, .tvos, .watchos, .visionos => detectDarwin(),
        .freebsd => detectFreeBSD(target),
        .openbsd => detectOpenBSD(),
        .netbsd => detectNetBSD(),
        .dragonfly => detectDragonFly(),
        else => .{
            .getopt_h = false,
            .inttypes_h = false,
            .memory_h = false,
            .stdint_h = false,
            .stdlib_h = false,
            .string_h = false,
            .strings_h = false,
            .sys_stat_h = false,
            .sys_types_h = false,
            .termios_h = false,
            .unistd_h = false,
        },
    };
}

// ── Linux ─────────────────────────────────────────────────────────────────────

fn detectLinux(target: std.Target) LibcHeaders {
    return .{
        .execinfo_h = !target.abi.isMusl(),
        .sys_epoll_h = true,
        .sys_personality_h = true,
        .sys_prctl_h = true,
        .sys_signalfd_h = true,
    };
}

// ── Darwin ────────────────────────────────────────────────────────────────────

fn detectDarwin() LibcHeaders {
    return .{
        .copyfile_h = true,
        .execinfo_h = true,
        .sys_event_h = true,
        .sys_ucred_h = true,
        .xlocale_h = true,
    };
}

// ── BSDs ──────────────────────────────────────────────────────────────────────

fn gte(os: std.Target.Os, comptime tag: std.Target.Os.Tag, ver: std.SemanticVersion) bool {
    return os.isAtLeast(tag, ver) orelse false;
}

fn detectFreeBSD(target: std.Target) LibcHeaders {
    return .{
        .execinfo_h = true,
        .sys_event_h = true,
        .sys_procctl_h = gte(target.os, .freebsd, .{ .major = 10, .minor = 1, .patch = 0 }), // https://man.freebsd.org/cgi/man.cgi?query=procctl&sektion=2
        .sys_ucred_h = true,
        .xlocale_h = true,
    };
}

fn detectOpenBSD() LibcHeaders {
    return .{
        .execinfo_h = true,
        .sys_event_h = true,
        .sys_ucred_h = true,
    };
}

fn detectNetBSD() LibcHeaders {
    return .{
        .atomic_h = true,
        .execinfo_h = true,
        .sys_event_h = true,
        .sys_ucred_h = true,
    };
}

fn detectDragonFly() LibcHeaders {
    return .{
        .execinfo_h = true,
        .sys_event_h = true,
        .sys_ucred_h = true,
    };
}
