// Generated by generate_libc_headers.py — do not edit.
// Regenerate with: python3 generate_libc_headers.py | zig fmt --stdin > libc_headers.zig
//
// Headers that are universally available on all supported POSIX targets default
// to true and are listed once. Headers whose presence varies by OS default to
// false and are set explicitly in each per-OS detection function.

const std = @import("std");

pub const LibcHeaders = struct {
    // Availability reference:
    //
    // arpa/inet.h:           glibc, musl, FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // atomic.h:              NetBSD
    // copyfile.h:            macOS
    // crtdefs.h:             Windows (mingw64)
    // execinfo.h:            glibc, FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // fcntl.h:               all supported targets
    // getopt.h:              all supported targets
    // ifaddrs.h:             glibc, musl, FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // inttypes.h:            all supported targets
    // linux/tcp.h:           glibc, musl
    // memory.h:              all supported targets
    // net/if.h:              glibc, musl, FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // netdb.h:               glibc, musl, FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // netinet/in.h:          glibc, musl, FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // netinet/tcp.h:         glibc, musl, FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // netinet/udp.h:         glibc, musl, FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // poll.h:                glibc, musl, FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // pwd.h:                 glibc, musl, FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // stdint.h:              all supported targets
    // stdlib.h:              all supported targets
    // string.h:              all supported targets
    // strings.h:             all supported targets
    // sys/epoll.h:           glibc, musl
    // sys/event.h:           FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // sys/eventfd.h:         glibc, musl, FreeBSD, NetBSD
    // sys/filio.h:           FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // sys/ioctl.h:           glibc, musl, FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // sys/personality.h:     glibc, musl
    // sys/prctl.h:           glibc, musl
    // sys/procctl.h:         FreeBSD 10.1+
    // sys/resource.h:        glibc, musl, FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // sys/select.h:          glibc, musl, FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // sys/signalfd.h:        glibc, musl
    // sys/sockio.h:          FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // sys/stat.h:            all supported targets
    // sys/types.h:           all supported targets
    // sys/ucred.h:           FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // sys/un.h:              glibc, musl, FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // termios.h:             glibc, musl, FreeBSD, NetBSD, OpenBSD, macOS, DragonFly
    // unistd.h:              all supported targets
    // uuid.h:                FreeBSD, NetBSD, OpenBSD, DragonFly
    // uuid/uuid.h:           macOS
    // xlocale.h:             FreeBSD, macOS

    // Always present
    fcntl_h: bool = true,
    getopt_h: bool = true,
    inttypes_h: bool = true,
    memory_h: bool = true,
    stdint_h: bool = true,
    stdlib_h: bool = true,
    string_h: bool = true,
    strings_h: bool = true,
    sys_stat_h: bool = true,
    sys_types_h: bool = true,
    unistd_h: bool = true,

    // OS-specific
    arpa_inet_h: bool = false,
    atomic_h: bool = false,
    copyfile_h: bool = false,
    crtdefs_h: bool = false,
    execinfo_h: bool = false,
    ifaddrs_h: bool = false,
    linux_tcp_h: bool = false,
    net_if_h: bool = false,
    netdb_h: bool = false,
    netinet_in_h: bool = false,
    netinet_tcp_h: bool = false,
    netinet_udp_h: bool = false,
    poll_h: bool = false,
    pwd_h: bool = false,
    sys_epoll_h: bool = false,
    sys_event_h: bool = false,
    sys_eventfd_h: bool = false,
    sys_filio_h: bool = false,
    sys_ioctl_h: bool = false,
    sys_personality_h: bool = false,
    sys_prctl_h: bool = false,
    sys_procctl_h: bool = false,
    sys_resource_h: bool = false,
    sys_select_h: bool = false,
    sys_signalfd_h: bool = false,
    sys_sockio_h: bool = false,
    sys_ucred_h: bool = false,
    sys_un_h: bool = false,
    termios_h: bool = false,
    uuid_h: bool = false,
    uuid_uuid_h: bool = false,
    xlocale_h: bool = false,
};

pub fn detect(target: std.Target) LibcHeaders {
    return switch (target.os.tag) {
        .linux => detectLinux(target),
        .macos, .ios, .tvos, .watchos, .visionos => detectDarwin(),
        .freebsd => detectFreeBSD(target),
        .openbsd => detectOpenBSD(),
        .netbsd => detectNetBSD(),
        .dragonfly => detectDragonFly(),
        .windows => detectWindows(),
        else => .{
            .fcntl_h = false,
            .getopt_h = false,
            .inttypes_h = false,
            .memory_h = false,
            .stdint_h = false,
            .stdlib_h = false,
            .string_h = false,
            .strings_h = false,
            .sys_stat_h = false,
            .sys_types_h = false,
            .unistd_h = false,
        },
    };
}

// ── Linux ─────────────────────────────────────────────────────────────────────

fn detectLinux(target: std.Target) LibcHeaders {
    return .{
        .arpa_inet_h = true,
        .execinfo_h = !target.abi.isMusl(),
        .ifaddrs_h = true,
        .linux_tcp_h = true,
        .net_if_h = true,
        .netdb_h = true,
        .netinet_in_h = true,
        .netinet_tcp_h = true,
        .netinet_udp_h = true,
        .poll_h = true,
        .pwd_h = true,
        .sys_epoll_h = true,
        .sys_eventfd_h = true,
        .sys_ioctl_h = true,
        .sys_personality_h = true,
        .sys_prctl_h = true,
        .sys_resource_h = true,
        .sys_select_h = true,
        .sys_signalfd_h = true,
        .sys_un_h = true,
        .termios_h = true,
    };
}

// ── Darwin ────────────────────────────────────────────────────────────────────

fn detectDarwin() LibcHeaders {
    return .{
        .arpa_inet_h = true,
        .copyfile_h = true,
        .execinfo_h = true,
        .ifaddrs_h = true,
        .net_if_h = true,
        .netdb_h = true,
        .netinet_in_h = true,
        .netinet_tcp_h = true,
        .netinet_udp_h = true,
        .poll_h = true,
        .pwd_h = true,
        .sys_event_h = true,
        .sys_filio_h = true,
        .sys_ioctl_h = true,
        .sys_resource_h = true,
        .sys_select_h = true,
        .sys_sockio_h = true,
        .sys_ucred_h = true,
        .sys_un_h = true,
        .termios_h = true,
        .uuid_uuid_h = true,
        .xlocale_h = true,
    };
}

// ── BSDs ──────────────────────────────────────────────────────────────────────

fn gte(os: std.Target.Os, comptime tag: std.Target.Os.Tag, ver: std.SemanticVersion) bool {
    return os.isAtLeast(tag, ver) orelse false;
}

fn detectFreeBSD(target: std.Target) LibcHeaders {
    return .{
        .arpa_inet_h = true,
        .execinfo_h = true,
        .ifaddrs_h = true,
        .net_if_h = true,
        .netdb_h = true,
        .netinet_in_h = true,
        .netinet_tcp_h = true,
        .netinet_udp_h = true,
        .poll_h = true,
        .pwd_h = true,
        .sys_event_h = true,
        .sys_eventfd_h = true,
        .sys_filio_h = true,
        .sys_ioctl_h = true,
        .sys_procctl_h = gte(target.os, .freebsd, .{ .major = 10, .minor = 1, .patch = 0 }), // https://man.freebsd.org/cgi/man.cgi?query=procctl&sektion=2
        .sys_resource_h = true,
        .sys_select_h = true,
        .sys_sockio_h = true,
        .sys_ucred_h = true,
        .sys_un_h = true,
        .termios_h = true,
        .uuid_h = true,
        .xlocale_h = true,
    };
}

fn detectOpenBSD() LibcHeaders {
    return .{
        .arpa_inet_h = true,
        .execinfo_h = true,
        .ifaddrs_h = true,
        .net_if_h = true,
        .netdb_h = true,
        .netinet_in_h = true,
        .netinet_tcp_h = true,
        .netinet_udp_h = true,
        .poll_h = true,
        .pwd_h = true,
        .sys_event_h = true,
        .sys_filio_h = true,
        .sys_ioctl_h = true,
        .sys_resource_h = true,
        .sys_select_h = true,
        .sys_sockio_h = true,
        .sys_ucred_h = true,
        .sys_un_h = true,
        .termios_h = true,
        .uuid_h = true,
    };
}

fn detectNetBSD() LibcHeaders {
    return .{
        .arpa_inet_h = true,
        .atomic_h = true,
        .execinfo_h = true,
        .ifaddrs_h = true,
        .net_if_h = true,
        .netdb_h = true,
        .netinet_in_h = true,
        .netinet_tcp_h = true,
        .netinet_udp_h = true,
        .poll_h = true,
        .pwd_h = true,
        .sys_event_h = true,
        .sys_eventfd_h = true,
        .sys_filio_h = true,
        .sys_ioctl_h = true,
        .sys_resource_h = true,
        .sys_select_h = true,
        .sys_sockio_h = true,
        .sys_ucred_h = true,
        .sys_un_h = true,
        .termios_h = true,
        .uuid_h = true,
    };
}

fn detectDragonFly() LibcHeaders {
    return .{
        .arpa_inet_h = true,
        .execinfo_h = true,
        .ifaddrs_h = true,
        .net_if_h = true,
        .netdb_h = true,
        .netinet_in_h = true,
        .netinet_tcp_h = true,
        .netinet_udp_h = true,
        .poll_h = true,
        .pwd_h = true,
        .sys_event_h = true,
        .sys_filio_h = true,
        .sys_ioctl_h = true,
        .sys_resource_h = true,
        .sys_select_h = true,
        .sys_sockio_h = true,
        .sys_ucred_h = true,
        .sys_un_h = true,
        .termios_h = true,
        .uuid_h = true,
    };
}

// ── Windows (mingw64) ─────────────────────────────────────────────────────────

fn detectWindows() LibcHeaders {
    return .{
        .crtdefs_h = true,
    };
}
